---
title: "in-class-ex-11"
description: |
  Introduction to R Shiny
author:
  - name: Ryan Chan
    url: https://www.linkedin.com/in/ryan-chan-a7021b5/
date: 07-17-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, warning = FALSE, fig.retina = 3)
```




```{r}

packages = c('igraph','tidygraph','ggraph','hms','textplot','tidyverse','lubridate','ggwordcloud','DT','wordcloud',
             'widyr','tidytext')

for(p in packages){
if(!require(p, character.only = T)){
  install.packages(p)
  }
  library(p, character.only = T)
}

```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```





```{r}



```





```{r}



```