---
title: "VAST Challenge - Mini-Challenge 3"
description: |
  Mini-Challenge 3
author:
  - name: Ryan Chan
    url: https://www.linkedin.com/in/ryan-chan-a7021b5/
date: 07-12-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, warning = FALSE, fig.retina = 3)
```


# 1. Introduction and Objectives


```{r}

packages = c('igraph','tidygraph','ggraph','hms','textplot','tidyverse','lubridate','ggwordcloud','DT','wordcloud',
             'widyr','tidytext','dplyr','clock','visNetwork','hms','qdapDictionaries',
             'corpus','syuzhet','greekLetters','textdata','plotly','patchwork','Rcpp')

for(p in packages){
if(!require(p, character.only = T)){
  install.packages(p)
  }
  library(p, character.only = T)
}

`%!in%` = Negate(`%in%`)

```



```{r}

mctext_files <- list.files(path = "data", pattern = '.csv$', full.names = TRUE) %>% 
  map(read_csv)

raw_data <- data.table::rbindlist(mctext_files, use.names = TRUE, idcol = "source")

write_rds(raw_data, "data/rds/raw_data.rds")

glimpse(raw_data)

```



```{r}


raw_data$timestamp <- paste(substring(raw_data$`date(yyyyMMddHHmmss)`,first = 9, last = 10),
                           substring(raw_data$`date(yyyyMMddHHmmss)`,first = 11, last = 12),sep=":")

raw_data$date <- paste(substring(raw_data$`date(yyyyMMddHHmmss)`, first = 1, last = 4),
                       substring(raw_data$`date(yyyyMMddHHmmss)`, first = 5, last = 6),
                       substring(raw_data$`date(yyyyMMddHHmmss)`, first = 7, last = 8),sep = "-")

raw_data$date <- parse_date(raw_data$date, format = "%Y-%m-%d")

raw_data$timestamp <- parse_time(raw_data$timestamp, format = "%AT")

raw_data$datetime <- paste(raw_data$date, raw_data$timestamp, sep = " ")
raw_data$datetime <- parse_date_time(raw_data$datetime, "%Y-%m-%d %H:%M:%S")
raw_data$time_block = cut(raw_data$datetime, breaks = "30 min")

glimpse(raw_data)

```



```{r}

#author_unique_list <- raw_data %>% distinct(raw_data$author)
#author_list <- as.list(author_unique_list)
author_list <- unique(raw_data$author)
raw_data$hashtags <- str_extract_all(raw_data$message,"(?<=#)\\w+\\b")
raw_data$hashtags[lengths(raw_data$hashtags) == 0] <- NA_character_
raw_data$hashtags <- as.character(raw_data$hashtags)
raw_data$retweet_source <- str_extract_all(raw_data$message,"(?<=RT @)\\S+\\b")
raw_data$retweet_source[lengths(raw_data$retweet_source) == 0] <- NA_character_
raw_data$retweet_source <- as.character(raw_data$retweet_source)
raw_data$cleaned_message <- str_replace_all(raw_data$message,"RT @\\S+\\s*\\b","")
raw_data$cleaned_message <- str_replace_all(raw_data$cleaned_message,"#\\w+\\s*\\b","")
raw_data$mentions <- ifelse(as.character(str_extract_all(raw_data$cleaned_message,"(?<=@)\\S+\\b")) %in% author_list, str_extract_all(raw_data$cleaned_message,"(?<=@)\\S+\\b"),ifelse (as.character(str_extract_all(raw_data$cleaned_message,"(?<=@)\\w+\\b")) %in% author_list,str_extract_all(raw_data$cleaned_message,"(?<=@)\\w+\\b"),NA_character_))
raw_data$mentions <- as.character(raw_data$mentions)
raw_data <- raw_data %>% mutate(mentions = ifelse(as.character(mentions) != as.character(author),mentions,NA_character_))
#raw_data <- raw_data %>% mutate(mentions = ifelse(as.character(mentions) %in% author_list,mentions,NA_character_))
raw_data$mentions[lengths(raw_data$mentions) == 0] <- NA_character_
raw_data$cleaned_message <- str_replace_all(raw_data$cleaned_message,"@\\S+\\s*\\b","")

```




```{r}

mb <- raw_data %>% filter(type == "mbdata")
cc <- raw_data %>% filter(type == "ccdata")

```


```{r}



```



```{r}

mb_words <- mb %>% 
  unnest_tokens(word, cleaned_message, drop = FALSE) %>%
  filter(str_detect(word, "[a-z']$"),
         !word %in% stop_words$word)

mb_words <- select(mb_words, -c(source, type, `date(yyyyMMddHHmmss)`, date, timestamp, message))

```

#############################################
Messages by Author
#############################################

```{r}

mb_messages_by_author <- mb %>% 
  count(author, cleaned_message)

```



```{r}

mb_messages_by_author_aggregated <- mb_messages_by_author %>% 
  group_by(author) %>% 
  summarize(unique_count = n(), total_count = sum(n), junk_check = total_count/unique_count) %>% 
  filter(junk_check > 1)



```



```{r}

ggplot(mb_messages_by_author_aggregated, aes())

```


#############################################
Words by Timeblock
#############################################


```{r}

mb_words_by_timeblock <- mb_words %>% 
  count(time_block, word, sort=TRUE)

```



```{r}

mb_words_by_timeblock_tfidf <- mb_words_by_timeblock %>% 
  bind_tf_idf(word, time_block, n) %>%
  arrange(desc(tf_idf))

```

#############################################
Words by Author
#############################################

```{r}

mb_words_by_author <- mb_words %>%
count(author, word, sort = TRUE) %>%
ungroup()

```



```{r}

mb_words_by_author$in_dictionary <- if_else (mb_words_by_author$word %in% GradyAugmented,0,1)
mb_words_by_author$sentiment <- get_sentiment(mb_words_by_author$word, method = "syuzhet")
mb_words_by_author$total_sentiment <- mb_words_by_author$sentiment*mb_words_by_author$n

nrc <- get_sentiments("nrc")


```



```{r}

mb_words_by_author_tfidf <- mb_words_by_author %>% 
  bind_tf_idf(word, author, n) %>%
  arrange(desc(tf_idf))

```



```{r}

mb_words_by_author_nested <- mb_words_by_author %>% 
  group_by(author) %>% 
  group_nest()

```



```{r}

set.seed(1234)
wordcloud(mb_words_by_author$word, mb_words_by_author$n, max.words = 300)

```



```{r}

mb_words_by_author_agg_sentiment <- mb_words_by_author %>% 
  group_by(author) %>% 
  summarise(grandtotal_sentiment = sum(total_sentiment)) %>% 
  arrange(desc(grandtotal_sentiment))

```




```{r}

mb_words_by_author_NotInDict <- mb_words_by_author %>%
  filter(in_dictionary > 0) %>% 
  group_by(author) %>% 
  summarise(sum(in_dictionary), data = list(word))

```



```{r}

datatable(mb_words_by_author_NotInDict)

```


#############################################
Retweet Network
#############################################


```{r}

RT_edges <- mb %>% 
  filter(!is.na(retweet_source)) %>% 
  transmute(source_label = author, target_label = as.character(retweet_source))

```



```{r}

RT_edges_agg <- RT_edges %>% 
  count(source_label, target_label) %>%
  rename(from = source_label, to = target_label)
  ungroup

```



```{r}

RT_source <- distinct(RT_edges, node = RT_edges$source_label)
RT_target <- distinct(RT_edges, node = as.character(RT_edges$target_label))
RT_node <- bind_rows(RT_source, RT_target)
RT_node <- RT_node %>% 
  distinct(node) %>% 
  rename(id = node)
RT_vis_node <- data.frame(id=RT_node$id, label= paste(RT_node$id), font.size=30)

```



```{r}

#RT_graph <- tbl_graph(nodes = RT_node, edges = RT_edges_agg, directed = TRUE)
#RT_graph

```



```{r}

#RT_network <- RT_graph %>% 
  #mutate(degree_centrality = centrality_degree()) %>%
  #ggraph(layout = "fr") +
  #geom_edge_link(aes(width=n),
  #alpha=0.2) +
  #scale_edge_width(range = c(0.1, 5)) +
  #geom_node_point(aes(colour = node,
  #size=degree_centrality))

#RT_network + theme_graph()

```



```{r}



```



```{r}

visNetwork(RT_vis_node,RT_edges_agg, idToLabel=TRUE) %>%
visNodes(color = list(background = "lightblue", 
                        border = "darkgreen",
                        highlight = "red"),
         labelHighlightBold = TRUE) %>% 
visIgraphLayout(layout = "layout_with_fr") %>% 
visOptions(highlightNearest = list(enabled = T, hover = T), 
           nodesIdSelection = T) %>% 
visLayout(randomSeed = 1234)

```

#####################################
Hastags
#####################################

```{r}

mb_hashtags <- mb %>%
  unnest(hashtags, keep_empty = TRUE)

```

#####################################
Mentions
#####################################

```{r}

mb_mentions <- mb %>%
  filter(!is.na(mentions)) %>% 
  unnest(mentions, keep_empty = FALSE)

```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```